-- 001_create_users_table.sql
-- Initialize database with users table

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create index on email for faster lookups
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- Insert sample data (102 users)
INSERT INTO users (name, email) VALUES
    ('Alice', 'alice@example.com'),
    ('Bob', 'bob@example.com'),
    ('Charlie Brown', 'charlie.brown@example.com'),
    ('Diana Prince', 'diana.prince@example.com'),
    ('Ethan Hunt', 'ethan.hunt@example.com'),
    ('Fiona Apple', 'fiona.apple@example.com'),
    ('George Miller', 'george.miller@example.com'),
    ('Hannah Montana', 'hannah.montana@example.com'),
    ('Ian McKellen', 'ian.mckellen@example.com'),
    ('Jessica Jones', 'jessica.jones@example.com'),
    ('Kevin Hart', 'kevin.hart@example.com'),
    ('Laura Palmer', 'laura.palmer@example.com'),
    ('Michael Scott', 'michael.scott@example.com'),
    ('Natasha Romanoff', 'natasha.romanoff@example.com'),
    ('Oscar Isaac', 'oscar.isaac@example.com'),
    ('Phoebe Buffay', 'phoebe.buffay@example.com'),
    ('Quinn Anderson', 'quinn.anderson@example.com'),
    ('Rachel Green', 'rachel.green@example.com'),
    ('Samuel Jackson', 'samuel.jackson@example.com'),
    ('Tina Turner', 'tina.turner@example.com'),
    ('Uma Thurman', 'uma.thurman@example.com'),
    ('Victoria Beckham', 'victoria.beckham@example.com'),
    ('William Smith', 'william.smith@example.com'),
    ('Xena Warrior', 'xena.warrior@example.com'),
    ('Yvonne Strahovski', 'yvonne.strahovski@example.com'),
    ('Zendaya Coleman', 'zendaya.coleman@example.com'),
    ('Aaron Paul', 'aaron.paul@example.com'),
    ('Bella Swan', 'bella.swan@example.com'),
    ('Chloe Grace', 'chloe.grace@example.com'),
    ('Daniel Craig', 'daniel.craig@example.com'),
    ('Emma Watson', 'emma.watson@example.com'),
    ('Finn Wolfhard', 'finn.wolfhard@example.com'),
    ('Gal Gadot', 'gal.gadot@example.com'),
    ('Henry Cavill', 'henry.cavill@example.com'),
    ('Isla Fisher', 'isla.fisher@example.com'),
    ('Jason Momoa', 'jason.momoa@example.com'),
    ('Katniss Everdeen', 'katniss.everdeen@example.com'),
    ('Leonardo DiCaprio', 'leonardo.dicaprio@example.com'),
    ('Megan Fox', 'megan.fox@example.com'),
    ('Nicolas Cage', 'nicolas.cage@example.com'),
    ('Olivia Wilde', 'olivia.wilde@example.com'),
    ('Patrick Stewart', 'patrick.stewart@example.com'),
    ('Quentin Tarantino', 'quentin.tarantino@example.com'),
    ('Rowan Atkinson', 'rowan.atkinson@example.com'),
    ('Scarlett Johansson', 'scarlett.johansson@example.com'),
    ('Tom Hanks', 'tom.hanks@example.com'),
    ('Ulla Albinsson', 'ulla.albinsson@example.com'),
    ('Viggo Mortensen', 'viggo.mortensen@example.com'),
    ('Will Smith', 'will.smith@example.com'),
    ('Xander Berkeley', 'xander.berkeley@example.com'),
    ('Yoko Ono', 'yoko.ono@example.com'),
    ('Zoe Kravitz', 'zoe.kravitz@example.com'),
    ('Adam Driver', 'adam.driver@example.com'),
    ('Brie Larson', 'brie.larson@example.com'),
    ('Chris Pratt', 'chris.pratt@example.com'),
    ('Danielle Panabaker', 'danielle.panabaker@example.com'),
    ('Emily Blunt', 'emily.blunt@example.com'),
    ('Florence Pugh', 'florence.pugh@example.com'),
    ('Gigi Hadid', 'gigi.hadid@example.com'),
    ('Hailey Baldwin', 'hailey.baldwin@example.com'),
    ('Iris West', 'iris.west@example.com'),
    ('John Boyega', 'john.boyega@example.com'),
    ('Keira Knightley', 'keira.knightley@example.com'),
    ('Liam Neeson', 'liam.neeson@example.com'),
    ('Margot Robbie', 'margot.robbie@example.com'),
    ('Nathan Drake', 'nathan.drake@example.com'),
    ('Oprah Winfrey', 'oprah.winfrey@example.com'),
    ('Priyanka Chopra', 'priyanka.chopra@example.com'),
    ('Rami Malek', 'rami.malek@example.com'),
    ('Saoirse Ronan', 'saoirse.ronan@example.com'),
    ('Tom Hardy', 'tom.hardy@example.com'),
    ('Utkarsh Ambudkar', 'utkarsh.ambudkar@example.com'),
    ('Vince Vaughn', 'vince.vaughn@example.com'),
    ('Wanda Maximoff', 'wanda.maximoff@example.com'),
    ('Ximena Duran', 'ximena.duran@example.com'),
    ('Yuki Uchida', 'yuki.uchida@example.com'),
    ('Zoe Saldana', 'zoe.saldana@example.com'),
    ('Andrew Garfield', 'andrew.garfield@example.com'),
    ('Bryce Dallas Howard', 'bryce.dallas.howard@example.com'),
    ('Chris Evans', 'chris.evans@example.com'),
    ('Dave Bautista', 'dave.bautista@example.com'),
    ('Eddie Redmayne', 'eddie.redmayne@example.com'),
    ('Felicity Jones', 'felicity.jones@example.com'),
    ('Glen Powell', 'glen.powell@example.com'),
    ('Hayley Atwell', 'hayley.atwell@example.com'),
    ('Idris Elba', 'idris.elba@example.com'),
    ('Jenna Ortega', 'jenna.ortega@example.com'),
    ('Keanu Reeves', 'keanu.reeves@example.com'),
    ('Lily James', 'lily.james@example.com'),
    ('Mark Ruffalo', 'mark.ruffalo@example.com'),
    ('Noomi Rapace', 'noomi.rapace@example.com'),
    ('Oscar Nuñez', 'oscar.nunez@example.com'),
    ('Pål Sverre Hagen', 'pal.hagen@example.com'),
    ('Robert Downey Jr', 'robert.downey@example.com'),
    ('Sasha Pieterse', 'sasha.pieterse@example.com'),
    ('Tom Cruise', 'tom.cruise@example.com'),
    ('Ushna Shah', 'ushna.shah@example.com'),
    ('Vanessa Hudgens', 'vanessa.hudgens@example.com'),
    ('Woody Harrelson', 'woody.harrelson@example.com'),
    ('Xochitl Gomez', 'xochitl.gomez@example.com'),
    ('Yara Shahidi', 'yara.shahidi@example.com'),
    ('Zara Larsson', 'zara.larsson@example.com')
ON CONFLICT (email) DO NOTHING;
